version: '3.8'
services:
  test_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fossil_test
    ports:
      - "5433:5432"  # Note: Using 5433 to avoid conflicts with any existing db
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  postgres_test_data: