services:
  update:
    build:
      dockerfile: Dockerfile.update
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - NODE_CONNECTION_STRING=${NODE_CONNECTION_STRING}
      - ROUTER_ENDPOINT=${ROUTER_ENDPOINT}
    depends_on:
      db:
        condition: service_healthy

  # Uncomment and modify the following section when ready to run the 'fix' service
  # fix:
  #   build:
  #     dockerfile: Dockerfile.fix
  #     context: .
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
  #     - NODE_CONNECTION_STRING=${NODE_CONNECTION_STRING}
  #     - ROUTER_ENDPOINT=${ROUTER_ENDPOINT}
  #   depends_on:
  #     update:
  #       condition: service_started

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RUST_LOG=info 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
