services:
  migrations:
    build:
      context: ..
      dockerfile: docker/Dockerfile.migrate
    networks:
      - local_network
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy

  indexer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.indexer
    ports:
      - "3000:3000"
    networks:
      - local_network
    env_file:
      - ../.env
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/postgres
      - ROUTER_ENDPOINT=0.0.0.0:3000
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - local_network
    volumes:
      - db_local_data:/var/lib/postgresql/local_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  local_network:
volumes:
  db_local_data:
