[build]
rustflags = [
    "-C", "instrument-coverage",
    "-C", "link-dead-code",
]

[env]
CARGO_INCREMENTAL = "0"
RUSTFLAGS = "-Cinstrument-coverage"
LLVM_PROFILE_FILE = "target/coverage/fossil-headers-db-%p-%m.profraw"
